'use strict';
// Paylaşılan dil sözlüğü. Hem ana süreç (main.js, steam-service.js) hem de
// renderer (preload üzerinden pencereye açılır) bunu kullanır, böylece metinler
// tek yerde tutulur.

const LANG = {
  tr: {
    // Giriş
    'login.subtitle': 'Steam hesabınla giriş yap. Şifren sadece Steam’e gider, hiçbir yere kaydedilmez.',
    'login.savedFor': '{name} için kayıtlı oturum var.',
    'login.resume': 'Devam et',
    'login.forget': 'Unut',
    'login.segPassword': 'Şifre ile',
    'login.segQr': 'QR kod ile',
    'login.accountLabel': 'Steam hesap adı',
    'login.passwordLabel': 'Şifre',
    'login.rememberLabel': 'Bu bilgisayarda oturumu hatırla',
    'login.rememberHint': 'Şifre saklanmaz; Windows’un güvenli alanına şifreli bir giriş anahtarı yazılır.',
    'login.rememberUnavailable': 'Bu bilgisayarda güvenli saklama yok, oturum hatırlanamaz.',
    'login.submit': 'Giriş yap',
    'login.connecting': 'Bağlanılıyor…',
    'login.qrPreparing': 'QR kodu hazırlanıyor…',
    'login.qrHelp': 'Telefonundaki Steam uygulamasında Steam Guard’a gir, QR kodu okut ve girişi onayla.',
    'login.qrScanned': 'Okundu. Şimdi telefondan girişi onayla.',
    'login.qrExpired': 'QR kodun süresi doldu. Aşağıdan yenile.',
    'login.qrGenFailed': 'QR görseli oluşturulamadı.',
    'login.qrSigning': 'Giriş yapılıyor…',
    'login.qrRefresh': 'QR kodu yenile',

    // Steam Guard
    'guard.titleCode': 'Steam Guard kodunu gir',
    'guard.titleEmail': 'E-posta kodunu gir',
    'guard.subEmail': 'Kod {email} adresine gönderildi.',
    'guard.subApp': 'Telefondaki Steam uygulamasında görünen kodu yaz.',
    'guard.wrong': 'Kod yanlış. Steam seni kilitlemesin diye biraz bekleyip yeni kod dene.',
    'guard.ariaLabel': 'Steam Guard kodu',
    'guard.submit': 'Kodu gönder',
    'guard.waitFor': 'Yeni kod için {s} sn bekle',
    'guard.cancel': 'Vazgeç',

    // Kenar çubuğu / gezinme
    'nav.games': 'Oyunlar',
    'nav.achievements': 'Başarımlar',
    'nav.settings': 'Ayarlar',

    'nav.stats': 'İstatistik',
    'orb.blockedSubName': '{name} engelliyor',
    'games.statusBlockedBy': '“{name}” başka yerde açık. Kapanınca idle devam eder.',
    'games.tplCards': 'Kartlı 20',
    'games.tplNever': 'Kartlı hızlı',
    'games.tplPicked': '{n} oyun seçildi',
    'ach.chipAll': 'Hepsi',
    'ach.chipNone': 'Hiç açılmamış',
    'ach.undo': 'Son işlemi geri al',
    'ach.undoConfirm': 'Son başarım işlemini geri almak istediğine emin misin?',
    'ach.undoOk': 'Geri alma başlatıldı.',
    'ach.undoFailed': 'Geri alınamadı.',
    'ach.doneSummary': '{games} oyunda {n} başarım işlendi.',
    'stats.title': 'İstatistikler',
    'stats.intro': 'Bu uygulama ile biriktirdiğin süre ve başarımlar kalıcı olarak saklanır; sıfırlanmaz.',
    'stats.refresh': 'Yenile',
    'stats.openFolder': 'Klasörü aç',
    'stats.openLogs': 'Log klasörü',
    'stats.topGames': 'En çok idle edilen oyunlar',
    'stats.recent': 'Son olaylar',
    'stats.totalIdle': 'Toplam idle',
    'stats.totalSessions': 'Oturum',
    'stats.totalUnlock': 'Açılan başarım',
    'stats.totalClear': 'Silinen başarım',
    'stats.emptyGames': 'Henüz idle kaydı yok.',
    'stats.emptyRecent': 'Henüz olay yok.',
    'stats.sessionSummary': 'Oturum: {time} · {n} oyun',
    'stats.evIdle': 'Idle {time} · {n} oyun',
    'stats.evUnlock': '{name}: {n} başarım açıldı',
    'stats.evClear': '{name}: {n} başarım silindi',
    'cmd.placeholder': 'Komut veya oyun ara…',
    'cmd.hint': '↑↓ seç · Enter çalıştır · Esc kapat · Ctrl+K',
    'cmd.empty': 'Sonuç yok',
    'cmd.tabGames': 'Oyunlar sekmesi',
    'cmd.tabAch': 'Başarımlar sekmesi',
    'cmd.tabStats': 'İstatistik sekmesi',
    'cmd.tabSet': 'Ayarlar sekmesi',
    'cmd.selCards': 'Tüm kartlıları seç',
    'cmd.clearSel': 'Seçimi temizle',
    'cmd.startIdle': 'Idle başlat',
    'cmd.stopIdle': 'Idle durdur',
    'be.tray.stats': 'İstatistikler',
    'be.tray.idlePaused': 'Idle duraklatıldı',
    'be.tray.idleBlocked': 'Idle engellendi',
    'be.ach.undoUnavailable': 'Geri alınacak işlem yok veya işlem sürüyor.',
    'sidebar.lists': 'Listelerim',
    'sidebar.newList': 'Yeni liste',
    'sidebar.mute': 'Sesi aç veya kapat',
    'sidebar.logout': 'Çıkış yap',
    'lists.empty': 'Henüz liste yok. Oyunları seçip + düğmesiyle liste yapabilirsin.',

    // Halka / durum
    'orb.off': 'Kapalı',
    'orb.offSub': 'Idle bekliyor',
    'orb.paused': 'Duraklatıldı',
    'orb.pausedSub': 'Başarım işlemi sürüyor',
    'orb.noConn': 'Bağlantı yok',
    'orb.reconnecting': 'Yeniden bağlanılıyor',
    'orb.blocked': 'Engellendi',
    'orb.blockedSub': 'Başka yerde oyun var',
    'orb.idlingSub': '{n} oyun idle',

    'loading.default': 'Kütüphane okunuyor…',
    'loading.progress': 'Kütüphane okunuyor… {loaded} / {total}',

    // Oyunlar sekmesi
    'games.searchPh': 'Oyun ara',
    'games.chipAll': 'Hepsi',
    'games.chipCards': 'Kartlı',
    'games.chipSel': 'Seçili',
    'games.selectVisible': 'Görünenleri seç',
    'games.selectCards': 'Kartlı oyunları seç',
    'games.clearSel': 'Temizle',
    'games.tagCards': 'Kartı var',
    'games.tagAch': 'Başarımı var',
    'games.emptyFiltered': 'Aramana uyan oyun yok. Farklı bir kelime dene.',
    'games.emptyNone': 'Kütüphanende oyun bulunamadı. Aile paylaşımıyla gelen oyunlar listelenmez.',
    'games.countLine': '{total} oyun, {sel} seçili',
    'games.pickGame': 'Oyun seç',
    'games.startSel': 'Seçilenleri başlat ({n})',
    'games.updateSel': 'Seçimi güncelle',
    'games.updateSelN': 'Seçimi güncelle ({n})',
    'games.stop': 'Durdur',
    'games.newList': 'Liste yap',
    'games.rotateLabel': 'Grup değişimi',
    'games.rotateUnit': 'dk',
    'games.groupMode': 'Grup modu',
    'games.groupModeHint': 'Kapalıyken seçtiğin tüm oyunlar tek seferde gönderilir, 32 sınırı uygulanmaz.',
    'games.statusPaused': 'Başarım işlemi bitene kadar idle duraklatıldı.',
    'games.statusReconnecting': 'Bağlantı koptu, Steam’e yeniden bağlanılıyor…',
    'games.statusBlocked': 'Bu hesapla başka bir yerde oyun oynanıyor. O oyun kapanınca idle kendiliğinden devam eder.',
    'games.statusUngrouped': '{total} oyun tek seferde gönderildi, {time}. Steam en fazla 32 oyunu sayar, fazlası sayılmayabilir.',
    'games.statusGrouped': '{playing} oyun idle ediliyor, {time}. Grup {batch}/{batches}, {rotateMin} dk’da bir değişir.',
    'games.statusPlain': '{playing} oyun idle ediliyor, {time}',
    'games.warnOverLimitGrouped': 'Steam aynı anda en fazla 32 oyunu sayar. Fazlası gruplar hâlinde sırayla döner.',
    'games.warnOverLimitUngrouped': 'Grup modu kapalı: {n} oyun tek seferde gönderilecek. Steam 32’den fazlasını saymayabilir.',
    'games.idleStartFailed': 'Idle başlatılamadı.',

    // Listeler
    'lists.tooMany': 'En fazla 60 liste yapabilirsin.',
    'lists.noOwnedGames': 'Bu listede bu hesapta bulunan oyun yok.',
    'lists.newTitle': 'Yeni liste',
    'lists.nameLabel': 'Liste adı',
    'lists.create': 'Oluştur',
    'lists.addSelectedN': 'Seçili {n} oyunu ekle',
    'lists.addSelectedNone': 'Önce oyun seçersen buraya ekleyebilirsin',
    'lists.created': '“{name}” listesi oluşturuldu.',
    'lists.renameTitle': 'Listeyi yeniden adlandır',
    'lists.save': 'Kaydet',
    'lists.pickGamesFirst': 'Önce Oyunlar sekmesinden oyun seç.',
    'lists.savedTo': 'Seçim “{name}” listesine kaydedildi.',
    'lists.confirmDelete': '“{name}” listesi silinsin mi?',
    'lists.started': '“{name}” listesi başlatıldı.',
    'lists.menuRename': 'Yeniden adlandır',
    'lists.menuSaveSel': 'Seçimi bu listeye kaydet',
    'lists.menuDelete': 'Listeyi sil',
    'lists.playTitle': 'Bu listeyi başlat',
    'lists.playAria': '{name} listesini başlat',
    'lists.moreTitle': 'Diğer işlemler',
    'lists.moreAria': '{name} liste menüsü',
    'lists.selectAria': 'Listedeki oyunları seç',

    'dlg.ok': 'Tamam',
    'dlg.cancel': 'Vazgeç',

    // Başarımlar sekmesi
    'ach.title': 'Başarımları aç',
    'ach.intro': 'Seçtiğin oyunların tüm başarımlarını açar. Bilgisayarında Steam’in açık ve bu hesapla giriş yapılmış olması gerekir. VAC korumalı oyunlar listelenmez. Tek tek seçmek istersen oyunun yanındaki menü düğmesine bas.',
    'ach.searchPh': 'Oyun ara',
    'ach.selectVisible': 'Görünenleri seç',
    'ach.clearSel': 'Temizle',
    'ach.pickGame': 'Oyun seç',
    'ach.unlockN': 'Başarımları aç ({n} oyun)',
    'ach.resetN': 'Başarımları sıfırla ({n} oyun)',
    'ach.cancel': 'İptal',
    'ach.pickOne': 'Tek tek seç',
    'ach.pickOneAria': '{name} başarımlarını tek tek seç',
    'ach.noAchievableGame': 'Başarımı olan bir oyun bulunamadı.',
    'ach.confirmUnlock': '{n} oyunun tüm başarımları açılacak. Devam edilsin mi?',
    'ach.confirmReset': '{n} oyunun tüm başarımları sıfırlanacak (kilitlenecek). Bu işlem geri alınamaz gibi düşünülmeli. Devam edilsin mi?',
    'ach.confirmUnlockSome': 'Seçili {n} başarım açılacak. Devam edilsin mi?',
    'ach.confirmResetSome': 'Seçili {n} başarım sıfırlanacak (kilitlenecek). Devam edilsin mi?',
    'ach.starting': 'Başlıyor…',
    'ach.startFailed': 'Başarım işlemi başlatılamadı.',
    'ach.notStarted': 'Başlatılamadı.',
    'ach.cancelled': 'İptal edildi.',
    'ach.done': 'Bitti.',
    'ach.opening': 'Açılıyor…',
    'ach.resetting': 'Sıfırlanıyor…',
    'ach.progressOf': '{i} / {total} oyun',
    'ach.progressCount': '{done} / {total}',
    'ach.resultFailed': 'Açılamadı.',
    'ach.resultFailedClear': 'Sıfırlanamadı.',
    'ach.resultAllAlready': 'Hepsi zaten açık ({n})',
    'ach.resultAllAlreadyLocked': 'Hepsi zaten kilitli ({n})',
    'ach.resultUnlocked': '{n} başarım açıldı',
    'ach.resultReset': '{n} başarım sıfırlandı',
    'ach.resultMixed': '{n} açıldı, {f} açılamadı',
    'ach.resultMixedClear': '{n} sıfırlandı, {f} sıfırlanamadı',

    'ach.detailDefaultTitle': 'Oyun',
    'ach.detailLoading': 'Başarımlar okunuyor…',
    'ach.detailReadFailed': 'Başarımlar okunamadı.',
    'ach.detailPartial': 'Açık/kapalı durumları okunamadı.',
    'ach.detailNote': 'Gerçek adlar okunamadı; teknik adların sadeleştirilmiş hali gösteriliyor. Ayarlardan Steam Web API anahtarı eklersen gerçek adlar, görseller ve açılma tarihleri gelir.',
    'ach.detailNoteLocal': 'Adlar ve görseller bilgisayarındaki Steam’den okundu. Açılma tarihleri için Ayarlar’dan Steam Web API anahtarı ekleyebilirsin.',
    'ach.detailNoteKeyFail': 'Steam Web API anahtarıyla bilgi alınamadı; anahtarını kontrol et. Şimdilik teknik adların sadeleştirilmiş hali gösteriliyor.',
    'ach.detailNoteApi': 'Adlar, görseller ve açılma tarihleri Steam Web API anahtarınla gösteriliyor.',
    'ach.hiddenTitle': 'Gizli başarım',
    'ach.unnamed': 'Başarım {n}',
    'ach.unlockedNoDate': 'Açık',
    'ach.progressText': '{done} / {total} başarım açık',
    'ach.rarityTip': 'Küresel açılma oranı: {p}%',
    'ach.selectAll': 'Hepsini seç',
    'ach.modeUnlock': 'Aç',
    'ach.modeReset': 'Sil',
    'ach.resetAll': 'Tümünü sıfırla',
    'ach.cancelBtn': 'Vazgeç',
    'ach.close': 'Kapat',
    'ach.selectToUnlock': 'Başarım seç',
    'ach.selectToReset': 'Sıfırlanacak başarım seç',
    'ach.selectedUnlockN': 'Seçilenleri aç ({n})',
    'ach.selectedResetN': 'Seçilenleri sil ({n})',
    'ach.alreadyUnlocked': 'Zaten açık',
    'ach.alreadyLocked': 'Zaten kilitli',
    'ach.notFound': 'Başarım bulunamadı.',
    'ach.resetAllConfirm': '“{name}” oyunundaki TÜM başarımlar sıfırlanacak (kilitlenecek). Devam edilsin mi?',

    // Ayarlar
    'settings.title': 'Ayarlar',
    'settings.startupH': 'Başlangıç',
    'settings.autoStartTitle': 'Bilgisayarla birlikte başlat',
    'settings.autoStartDesc': 'Windows açıldığında uygulama kendiliğinden başlar.',
    'settings.startHiddenTitle': 'Windows ile başlayınca gizli aç',
    'settings.startHiddenDesc': 'Pencere gösterilmez, sadece tepsi simgesi görünür.',
    'settings.autoIdleTitle': 'Açılışta idle’ı başlat',
    'settings.autoIdleHintNeed': 'Bunun çalışması için “Oturumu hatırla” ile giriş yapmış olman gerekir.',
    'settings.autoIdleHint': 'Kayıtlı oturumla giriş yapar ve en son başlattığın seçimi idle etmeye devam eder.',
    'settings.windowH': 'Pencere',
    'settings.closeToTrayTitle': 'Kapat tuşu tepsiye küçültsün',
    'settings.closeToTrayDesc': 'Pencereyi kapatınca uygulama arka planda çalışmaya devam eder, idle durmaz.',
    'settings.minToTrayTitle': 'Simge durumuna küçültünce tepsiye gizle',
    'settings.minToTrayDesc': 'Görev çubuğunda yer kaplamaz, tepsi simgesinden açılır.',
    'settings.steamH': 'Steam',
    'settings.personaTitle': 'Steam’deki durumum',
    'settings.personaDesc': 'Çevrimiçi seçiliyken idle sırasında adın Steam’de yeşil görünür ve oyun oynuyor gösterir.',
    'settings.personaOnline': 'Çevrimiçi',
    'settings.personaInvisible': 'Görünmez',
    'settings.personaKeep': 'Elleme',
    'settings.apiKeyTitle': 'Steam Web API anahtarı (isteğe bağlı)',
    'settings.apiKeyDesc': 'Başarımların gerçek adını, görselini ve açılma tarihini göstermek için kullanılır. Boş bırakırsan uygulama eskisi gibi çalışır.',
    'settings.apiKeyLink': 'Ücretsiz anahtarını buradan al →',
    'settings.apiKeyPh': 'Anahtarı yapıştır',
    'settings.apiKeyShow': 'Göster',
    'settings.apiKeyHide': 'Gizle',
    'settings.apiKeySaved': 'Anahtar kaydedildi.',
    'settings.apiKeyCleared': 'Anahtar silindi.',
    'settings.notifH': 'Bildirim ve ses',
    'settings.notifTitle': 'Windows bildirimleri',
    'settings.notifDesc': 'Başarımlar açılınca ve idle duraklayınca bildirim gösterir. Steam’in kendi başarım balonu sadece oyunun içinden çıktığı için uygulamadaki bildirimi kullanırız.',
    'settings.soundTitle': 'Sesler',
    'settings.soundDesc': 'Seçim, başlatma ve bitiş sesleri.',
    
    'settings.themeH': 'Görünüm',
    'settings.themeTitle': 'Renk teması',
        'settings.themeAurora': 'Aurora',
    'settings.themeGoth': 'Goth',
        'settings.themeNova': 'Nova',
        'settings.langH': 'Dil',
    'settings.langTitle': 'Uygulama dili',
    'settings.langDesc': 'Arayüz dilini değiştirir.',
    'settings.langTr': 'Türkçe',
    'settings.langEn': 'English',

    // Ana süreç: giriş / oturum
    'be.login.needFields': 'Hesap adını ve şifreyi yaz.',
    'be.resume.noSession': 'Kayıtlı oturum bulunamadı.',
    'be.needLogin': 'Önce Steam’e giriş yapmalısın.',

    // Ana süreç: idle
    'be.idle.pickGame': 'Idle için en az bir oyun seç.',

    // Ana süreç: başarımlar
    'be.ach.busy': 'Başarım işlemi zaten sürüyor.',
    'be.ach.pickGame': 'Listeden en az bir oyun seç.',
    'be.ach.gameUnavailable': 'Bu oyun için başarım açılamıyor.',
    'be.ach.gameUnavailableClear': 'Bu oyun için başarım sıfırlanamıyor.',
    'be.ach.pickAchievement': 'En az bir başarım seç.',
    'be.ach.listUnavailable': 'Bu oyun için başarım listesi alınamadı.',
    'be.ach.fetchFailed': 'Başarım listesi Steam’den alınamadı. İnternetini kontrol et.',
    'be.ach.noneAvailable': 'Bu oyunda açılabilir başarım bulunamadı.',
    'be.ach.skipped': 'Atlandı, Steam istemcisi bulunamadı.',
    'be.ach.statusReadFailed': 'Durumlar okunamadı, hepsi açılabilir varsayıldı.',
    'be.ach.helperSpawnFailed': 'Yardımcı işlem başlatılamadı.',
    'be.ach.helperCrashed': 'Yardımcı işlem beklenmedik şekilde kapandı.',
    'be.ach.clientConnectFailed': 'Steam istemcisine bağlanılamadı. Steam’i aç, bu hesapla giriş yap ve oyunun bu hesapta olduğundan emin ol.',
    'be.ach.invalidRequest': 'Geçersiz istek.',
    'be.ach.unexpectedError': 'Beklenmedik bir hata oluştu.',

    // Bildirimler
    'be.notify.idlePausedTitle': 'Idle duraklatıldı',
    'be.notify.idlePausedBody': 'Bu hesapla başka bir yerde oyun oynanıyor. O oyun kapanınca idle kendiliğinden devam eder.',
    'be.notify.idleResumedTitle': 'Idle devam ediyor',
    'be.notify.idleResumedBody': 'Diğer oyun kapandı, idle yeniden başladı.',
    'be.notify.achUnlockedBody': '{n} başarım açıldı',
    'be.notify.achResetBody': '{n} başarım sıfırlandı',
    'be.notify.achBulkUnlockedTitle': 'Başarımlar açıldı',
    'be.notify.achBulkResetTitle': 'Başarımlar sıfırlandı',
    'be.notify.achBulkUnlockedBody': '{games} oyunda toplam {n} başarım açıldı.',
    'be.notify.achBulkResetBody': '{games} oyunda toplam {n} başarım sıfırlandı.',
    'be.notify.idleStartedBody': '{n} oyun idle ediliyor.',

    // Tepsi
    'be.tray.open': 'Aç',
    'be.tray.idleOff': 'Idle kapalı',
    'be.tray.idleOnN': '{n} oyun idle ediliyor',
    'be.tray.stopIdle': 'Idle’ı durdur',
    'be.tray.startLast': 'Son seçimi başlat',
    'be.tray.quit': 'Çıkış',
    'be.close.message': 'Uygulamayı kapatmak istiyor musun?',
    'be.close.detail': 'Tepsiye küçültürsen idle arka planda devam eder. Görev çubuğunda yer kaplamaz, gizli simgelerden açabilirsin.',
    'be.close.toTray': 'Tepsiye küçült',
    'be.close.quit': 'Uygulamayı kapat',
    'be.close.cancel': 'Vazgeç',
    'be.close.trayTip': 'Tepsiye küçültüldü. Bildirim alanındaki (gizli simgeler) ikondan tekrar açabilirsin.',
    'be.close.quitDetail': 'Uygulama tamamen kapanacak, idle de durur.',

    // Steam servis hataları
    'be.steam.badPassword': 'Hesap adı veya şifre yanlış.',
    'be.steam.badPasswordToken': 'Kayıtlı oturum artık geçerli değil. Yeniden giriş yap.',
    'be.steam.accessDenied': 'Steam girişi reddetti. Bilgilerini kontrol edip tekrar dene.',
    'be.steam.accessDeniedToken': 'Kayıtlı oturumun süresi dolmuş. Yeniden giriş yap.',
    'be.steam.rateLimit': 'Çok fazla giriş denemesi yapıldı. Birkaç dakika bekleyip tekrar dene.',
    'be.steam.guardWrong': 'Steam Guard kodu yanlış. Tekrar giriş yapıp yeni kodu dene.',
    'be.steam.loggedInElsewhere': 'Bu hesapla başka bir yerde oturum açıldığı için bağlantı defalarca kesildi. Aynı hesapla giriş yapan başka bir idle programını ya da bu uygulamanın ikinci kopyasını (görev çubuğundaki gizli simgelere de bak) kapatıp tekrar giriş yap.',
    'be.steam.noConnection': 'Steam’e bağlanılamadı. İnternet bağlantını kontrol edip tekrar dene.',
    'be.steam.unknown': 'Steam hatası: {code}.',
    'be.steam.unknownCode': 'bilinmiyor',
    'be.steam.guardNoneNow': 'Şu an kod istenmiyor.',
    'be.steam.guardWait': 'Steam kilitlenmesin diye biraz beklemen gerek.',
    'be.steam.guardEmpty': 'Kodu yaz.',
    'be.steam.qrFailed': 'QR girişi tamamlanamadı. Yeniden dene.',
    'be.steam.qrGenFailed': 'QR oluşturulamadı. İnternet bağlantını kontrol edip tekrar dene.'
  },

  en: {
    'login.subtitle': 'Sign in with your Steam account. Your password is sent only to Steam — it\u2019s never saved or logged.',
    'login.savedFor': 'There\u2019s a saved session for {name}.',
    'login.resume': 'Continue',
    'login.forget': 'Forget',
    'login.segPassword': 'With password',
    'login.segQr': 'With QR code',
    'login.accountLabel': 'Steam account name',
    'login.passwordLabel': 'Password',
    'login.rememberLabel': 'Remember session on this computer',
    'login.rememberHint': 'Not your password — a Windows-encrypted login key is stored instead.',
    'login.rememberUnavailable': 'Secure storage isn\u2019t available on this computer, so sessions can\u2019t be remembered.',
    'login.submit': 'Sign in',
    'login.connecting': 'Connecting…',
    'login.qrPreparing': 'Preparing the QR code…',
    'login.qrHelp': 'Open the Steam app on your phone, scan the QR code from the Steam Guard section, and confirm the sign-in.',
    'login.qrScanned': 'Scanned. Now confirm the sign-in on your phone.',
    'login.qrExpired': 'The QR code expired. Refresh it below.',
    'login.qrGenFailed': 'Couldn\u2019t generate the QR image.',
    'login.qrSigning': 'Signing in…',
    'login.qrRefresh': 'Refresh QR code',

    'guard.titleCode': 'Enter your Steam Guard code',
    'guard.titleEmail': 'Enter the email code',
    'guard.subEmail': 'The code was sent to {email}.',
    'guard.subApp': 'Type the code shown in the Steam app on your phone.',
    'guard.wrong': 'Wrong code. Wait a bit before requesting a new one so Steam doesn\u2019t lock you out.',
    'guard.ariaLabel': 'Steam Guard code',
    'guard.submit': 'Send code',
    'guard.waitFor': 'Wait {s}s for a new code',
    'guard.cancel': 'Cancel',

    'nav.games': 'Games',
    'nav.achievements': 'Achievements',
    'nav.settings': 'Settings',

    'nav.stats': 'Stats',
    'orb.blockedSubName': 'Blocked by {name}',
    'games.statusBlockedBy': '“{name}” is running elsewhere. Idle resumes when it closes.',
    'games.tplCards': 'Cards ×20',
    'games.tplNever': 'Cards quick',
    'games.tplPicked': '{n} games selected',
    'ach.chipAll': 'All',
    'ach.chipNone': 'Never unlocked',
    'ach.undo': 'Undo last',
    'ach.undoConfirm': 'Undo the last achievement action?',
    'ach.undoOk': 'Undo started.',
    'ach.undoFailed': 'Could not undo.',
    'ach.doneSummary': 'Processed {n} achievements across {games} games.',
    'stats.title': 'Statistics',
    'stats.intro': 'Hours and achievements from this app are stored permanently and never reset.',
    'stats.refresh': 'Refresh',
    'stats.openFolder': 'Open folder',
    'stats.openLogs': 'Open logs',
    'stats.topGames': 'Most idled games',
    'stats.recent': 'Recent activity',
    'stats.totalIdle': 'Total idle',
    'stats.totalSessions': 'Sessions',
    'stats.totalUnlock': 'Unlocked',
    'stats.totalClear': 'Cleared',
    'stats.emptyGames': 'No idle records yet.',
    'stats.emptyRecent': 'No events yet.',
    'stats.sessionSummary': 'Session: {time} · {n} games',
    'stats.evIdle': 'Idle {time} · {n} games',
    'stats.evUnlock': '{name}: unlocked {n}',
    'stats.evClear': '{name}: cleared {n}',
    'cmd.placeholder': 'Search commands or games…',
    'cmd.hint': '↑↓ select · Enter run · Esc close · Ctrl+K',
    'cmd.empty': 'No results',
    'cmd.tabGames': 'Games tab',
    'cmd.tabAch': 'Achievements tab',
    'cmd.tabStats': 'Stats tab',
    'cmd.tabSet': 'Settings tab',
    'cmd.selCards': 'Select all with cards',
    'cmd.clearSel': 'Clear selection',
    'cmd.startIdle': 'Start idle',
    'cmd.stopIdle': 'Stop idle',
    'be.tray.stats': 'Statistics',
    'be.tray.idlePaused': 'Idle paused',
    'be.tray.idleBlocked': 'Idle blocked',
    'be.ach.undoUnavailable': 'Nothing to undo, or an operation is running.',
    'sidebar.lists': 'My lists',
    'sidebar.newList': 'New list',
    'sidebar.mute': 'Toggle sound',
    'sidebar.logout': 'Log out',
    'lists.empty': 'No lists yet. Select some games and use the + button to make one.',

    'orb.off': 'Off',
    'orb.offSub': 'Idle is waiting',
    'orb.paused': 'Paused',
    'orb.pausedSub': 'Achievement task running',
    'orb.noConn': 'No connection',
    'orb.reconnecting': 'Reconnecting',
    'orb.blocked': 'Blocked',
    'orb.blockedSub': 'Playing elsewhere',
    'orb.idlingSub': 'Idling {n} games',

    'loading.default': 'Reading your library…',
    'loading.progress': 'Reading your library… {loaded} / {total}',

    'games.searchPh': 'Search games',
    'games.chipAll': 'All',
    'games.chipCards': 'Card drops',
    'games.chipSel': 'Selected',
    'games.selectVisible': 'Select visible',
    'games.selectCards': 'Select card-drop games',
    'games.clearSel': 'Clear',
    'games.tagCards': 'Has card drops',
    'games.tagAch': 'Has achievements',
    'games.emptyFiltered': 'No games match your search. Try a different word.',
    'games.emptyNone': 'No games found in your library. Family-shared games aren\u2019t listed.',
    'games.countLine': '{total} games, {sel} selected',
    'games.pickGame': 'Pick a game',
    'games.startSel': 'Start selected ({n})',
    'games.updateSel': 'Update selection',
    'games.updateSelN': 'Update selection ({n})',
    'games.stop': 'Stop',
    'games.newList': 'Make a list',
    'games.rotateLabel': 'Group switch',
    'games.rotateUnit': 'min',
    'games.groupMode': 'Group mode',
    'games.groupModeHint': 'When off, all selected games are sent at once \u2014 the 32-game limit doesn\u2019t apply.',
    'games.statusPaused': 'Idle is paused until the achievement task finishes.',
    'games.statusReconnecting': 'Connection lost \u2014 reconnecting to Steam…',
    'games.statusBlocked': 'A game is running elsewhere on this account. Idle resumes on its own once it closes.',
    'games.statusUngrouped': '{total} games sent at once, {time}. Steam counts at most 32 \u2014 the rest may not register.',
    'games.statusGrouped': 'Idling {playing} games, {time}. Group {batch}/{batches}, switching every {rotateMin} min.',
    'games.statusPlain': 'Idling {playing} games, {time}',
    'games.warnOverLimitGrouped': 'Steam counts at most 32 games at once. The rest rotate through in groups.',
    'games.warnOverLimitUngrouped': 'Group mode is off: {n} games will be sent at once. Steam may not count more than 32.',
    'games.idleStartFailed': 'Couldn\u2019t start idling.',

    'lists.tooMany': 'You can make up to 60 lists.',
    'lists.noOwnedGames': 'None of this list\u2019s games are on this account.',
    'lists.newTitle': 'New list',
    'lists.nameLabel': 'List name',
    'lists.create': 'Create',
    'lists.addSelectedN': 'Add the {n} selected games',
    'lists.addSelectedNone': 'Select games first to add them here',
    'lists.created': 'List \u201c{name}\u201d created.',
    'lists.renameTitle': 'Rename list',
    'lists.save': 'Save',
    'lists.pickGamesFirst': 'First pick games from the Games tab.',
    'lists.savedTo': 'Selection saved to \u201c{name}\u201d.',
    'lists.confirmDelete': 'Delete the list \u201c{name}\u201d?',
    'lists.started': 'List \u201c{name}\u201d started.',
    'lists.menuRename': 'Rename',
    'lists.menuSaveSel': 'Save selection to this list',
    'lists.menuDelete': 'Delete list',
    'lists.playTitle': 'Start this list',
    'lists.playAria': 'Start the {name} list',
    'lists.moreTitle': 'More actions',
    'lists.moreAria': '{name} list menu',
    'lists.selectAria': 'Select this list\u2019s games',

    'dlg.ok': 'OK',
    'dlg.cancel': 'Cancel',

    'ach.title': 'Unlock achievements',
    'ach.intro': 'Unlocks every achievement for the games you pick. Steam must be open on this computer and signed in with this account. VAC-protected games aren\u2019t listed. Use the button next to a game to pick achievements one by one.',
    'ach.searchPh': 'Search games',
    'ach.selectVisible': 'Select visible',
    'ach.clearSel': 'Clear',
    'ach.pickGame': 'Pick a game',
    'ach.unlockN': 'Unlock achievements ({n} games)',
    'ach.resetN': 'Reset achievements ({n} games)',
    'ach.cancel': 'Cancel',
    'ach.pickOne': 'Pick individually',
    'ach.pickOneAria': 'Pick {name}\u2019s achievements individually',
    'ach.noAchievableGame': 'No game with achievements found.',
    'ach.confirmUnlock': 'This will unlock every achievement in {n} games. Continue?',
    'ach.confirmReset': 'This will reset (lock) every achievement in {n} games. Treat this as irreversible. Continue?',
    'ach.confirmUnlockSome': 'This will unlock {n} selected achievements. Continue?',
    'ach.confirmResetSome': 'This will reset (lock) {n} selected achievements. Continue?',
    'ach.starting': 'Starting…',
    'ach.startFailed': 'Couldn\u2019t start the achievement task.',
    'ach.notStarted': 'Couldn\u2019t start.',
    'ach.cancelled': 'Cancelled.',
    'ach.done': 'Done.',
    'ach.opening': 'Unlocking…',
    'ach.resetting': 'Resetting…',
    'ach.progressOf': '{i} / {total} games',
    'ach.progressCount': '{done} / {total}',
    'ach.resultFailed': 'Couldn\u2019t unlock.',
    'ach.resultFailedClear': 'Couldn\u2019t reset.',
    'ach.resultAllAlready': 'All already unlocked ({n})',
    'ach.resultAllAlreadyLocked': 'All already locked ({n})',
    'ach.resultUnlocked': '{n} achievements unlocked',
    'ach.resultReset': '{n} achievements reset',
    'ach.resultMixed': '{n} unlocked, {f} failed',
    'ach.resultMixedClear': '{n} reset, {f} failed',

    'ach.detailDefaultTitle': 'Game',
    'ach.detailLoading': 'Reading achievements…',
    'ach.detailReadFailed': 'Couldn\u2019t read achievements.',
    'ach.detailPartial': 'Couldn\u2019t read unlock status.',
    'ach.detailNote': 'Couldn\u2019t read the real names, so a cleaned-up version of the technical name is shown. Add a Steam Web API key in Settings to get real names, icons and unlock dates.',
    'ach.detailNoteLocal': 'Names and icons were read from the Steam client on this computer. Add a Steam Web API key in Settings to also see unlock dates.',
    'ach.detailNoteKeyFail': 'Couldn\u2019t get data with the Steam Web API key \u2014 please check the key. Showing cleaned-up technical names for now.',
    'ach.detailNoteApi': 'Names, icons and unlock dates are shown using your Steam Web API key.',
    'ach.hiddenTitle': 'Hidden achievement',
    'ach.unnamed': 'Achievement {n}',
    'ach.unlockedNoDate': 'Unlocked',
    'ach.progressText': '{done} / {total} achievements unlocked',
    'ach.rarityTip': 'Global unlock rate: {p}%',
    'ach.selectAll': 'Select all',
    'ach.modeUnlock': 'Unlock',
    'ach.modeReset': 'Reset',
    'ach.resetAll': 'Reset all',
    'ach.cancelBtn': 'Cancel',
    'ach.close': 'Close',
    'ach.selectToUnlock': 'Pick achievements',
    'ach.selectToReset': 'Pick achievements to reset',
    'ach.selectedUnlockN': 'Unlock selected ({n})',
    'ach.selectedResetN': 'Reset selected ({n})',
    'ach.alreadyUnlocked': 'Already unlocked',
    'ach.alreadyLocked': 'Already locked',
    'ach.notFound': 'No achievements found.',
    'ach.resetAllConfirm': 'ALL achievements in \u201c{name}\u201d will be reset (locked). Continue?',

    'settings.title': 'Settings',
    'settings.startupH': 'Startup',
    'settings.autoStartTitle': 'Start with your computer',
    'settings.autoStartDesc': 'The app launches on its own when Windows starts.',
    'settings.startHiddenTitle': 'Start hidden with Windows',
    'settings.startHiddenDesc': 'The window stays hidden \u2014 only the tray icon shows.',
    'settings.autoIdleTitle': 'Start idling on launch',
    'settings.autoIdleHintNeed': 'This needs you to have signed in with \u201cRemember session\u201d for it to work.',
    'settings.autoIdleHint': 'Signs in with your saved session and keeps idling your last selection.',
    'settings.windowH': 'Window',
    'settings.closeToTrayTitle': 'Close button minimizes to tray',
    'settings.closeToTrayDesc': 'Closing the window keeps the app running in the background \u2014 idling doesn\u2019t stop.',
    'settings.minToTrayTitle': 'Minimize to the tray',
    'settings.minToTrayDesc': 'Won\u2019t take up space on the taskbar \u2014 reopen it from the tray icon.',
    'settings.steamH': 'Steam',
    'settings.personaTitle': 'My Steam status',
    'settings.personaDesc': 'With Online selected, your name shows green on Steam while idling and appears as playing.',
    'settings.personaOnline': 'Online',
    'settings.personaInvisible': 'Invisible',
    'settings.personaKeep': 'Leave as-is',
    'settings.apiKeyTitle': 'Steam Web API key (optional)',
    'settings.apiKeyDesc': 'Used to show achievements\u2019 real names, icons and unlock dates. Leave it empty and the app works as before.',
    'settings.apiKeyLink': 'Get your free key here \u2192',
    'settings.apiKeyPh': 'Paste your key',
    'settings.apiKeyShow': 'Show',
    'settings.apiKeyHide': 'Hide',
    'settings.apiKeySaved': 'Key saved.',
    'settings.apiKeyCleared': 'Key removed.',
    'settings.notifH': 'Notifications & sound',
    'settings.notifTitle': 'Windows notifications',
    'settings.notifDesc': 'Shows a notification when achievements unlock or idling pauses. Since Steam\u2019s own achievement popup only appears from inside the game, the app shows this instead.',
    'settings.soundTitle': 'Sounds',
    'settings.soundDesc': 'Selection, start, and finish sounds.',
    
    'settings.themeH': 'Appearance',
    'settings.themeTitle': 'Color theme',
        'settings.themeAurora': 'Aurora',
    'settings.themeGoth': 'Goth',
        'settings.themeNova': 'Nova',
        'settings.langH': 'Language',
    'settings.langTitle': 'App language',
    'settings.langDesc': 'Changes the interface language.',
    'settings.langTr': 'Turkish',
    'settings.langEn': 'English',

    'be.login.needFields': 'Enter your account name and password.',
    'be.resume.noSession': 'No saved session found.',
    'be.needLogin': 'You need to sign in to Steam first.',

    'be.idle.pickGame': 'Pick at least one game to idle.',

    'be.ach.busy': 'An achievement task is already running.',
    'be.ach.pickGame': 'Pick at least one game from the list.',
    'be.ach.gameUnavailable': 'Achievements aren\u2019t available for this game.',
    'be.ach.gameUnavailableClear': 'Achievements can\u2019t be reset for this game.',
    'be.ach.pickAchievement': 'Pick at least one achievement.',
    'be.ach.listUnavailable': 'Couldn\u2019t get the achievement list for this game.',
    'be.ach.fetchFailed': 'Couldn\u2019t fetch the achievement list from Steam. Check your internet connection.',
    'be.ach.noneAvailable': 'This game has no unlockable achievements.',
    'be.ach.skipped': 'Skipped \u2014 the Steam client wasn\u2019t found.',
    'be.ach.statusReadFailed': 'Couldn\u2019t read the status \u2014 assuming everything is unlockable.',
    'be.ach.helperSpawnFailed': 'Couldn\u2019t start the helper process.',
    'be.ach.helperCrashed': 'The helper process closed unexpectedly.',
    'be.ach.clientConnectFailed': 'Couldn\u2019t connect to the Steam client. Open Steam, sign in with this account, and make sure the game is on this account.',
    'be.ach.invalidRequest': 'Invalid request.',
    'be.ach.unexpectedError': 'An unexpected error occurred.',

    'be.notify.idlePausedTitle': 'Idling paused',
    'be.notify.idlePausedBody': 'A game is running elsewhere on this account. Idling resumes on its own once it closes.',
    'be.notify.idleResumedTitle': 'Idling resumed',
    'be.notify.idleResumedBody': 'The other game closed \u2014 idling started again.',
    'be.notify.achUnlockedBody': '{n} achievements unlocked',
    'be.notify.achResetBody': '{n} achievements reset',
    'be.notify.achBulkUnlockedTitle': 'Achievements unlocked',
    'be.notify.achBulkResetTitle': 'Achievements reset',
    'be.notify.achBulkUnlockedBody': '{n} achievements unlocked across {games} games.',
    'be.notify.achBulkResetBody': '{n} achievements reset across {games} games.',
    'be.notify.idleStartedBody': 'Idling {n} games.',

    'be.tray.open': 'Open',
    'be.tray.idleOff': 'Idle is off',
    'be.tray.idleOnN': 'Idling {n} games',
    'be.tray.stopIdle': 'Stop idling',
    'be.tray.startLast': 'Start last selection',
    'be.tray.quit': 'Quit',
    'be.close.message': 'Do you want to close the app?',
    'be.close.detail': 'Minimize to tray to keep idling in the background. It won\'t take taskbar space — open it from the notification area.',
    'be.close.toTray': 'Minimize to tray',
    'be.close.quit': 'Quit the app',
    'be.close.cancel': 'Cancel',
    'be.close.trayTip': 'Minimized to the tray. Open it again from the notification area (hidden icons).',
    'be.close.quitDetail': 'The app will quit completely and idling will stop.',

    'be.steam.badPassword': 'Account name or password is incorrect.',
    'be.steam.badPasswordToken': 'The saved session is no longer valid. Sign in again.',
    'be.steam.accessDenied': 'Steam refused the sign-in. Check your details and try again.',
    'be.steam.accessDeniedToken': 'The saved session expired. Sign in again.',
    'be.steam.rateLimit': 'Too many sign-in attempts. Wait a few minutes and try again.',
    'be.steam.guardWrong': 'The Steam Guard code is wrong. Sign in again and try the new code.',
    'be.steam.loggedInElsewhere': 'Disconnected repeatedly because this account signed in somewhere else. Close any other idle program using this account, or a second copy of this app (check the hidden tray icons too), then sign in again.',
    'be.steam.noConnection': 'Couldn\u2019t connect to Steam. Check your internet connection and try again.',
    'be.steam.unknown': 'Steam error: {code}.',
    'be.steam.unknownCode': 'unknown',
    'be.steam.guardNoneNow': 'No code is being requested right now.',
    'be.steam.guardWait': 'Wait a bit so Steam doesn\u2019t lock you out.',
    'be.steam.guardEmpty': 'Enter the code.',
    'be.steam.qrFailed': 'The QR sign-in couldn\u2019t complete. Try again.',
    'be.steam.qrGenFailed': 'Couldn\u2019t generate the QR code. Check your internet connection and try again.'
  }
};

function t(lang, key, vars) {
  const dict = LANG[lang] || LANG.tr;
  let s = dict[key] != null ? dict[key] : (LANG.tr[key] != null ? LANG.tr[key] : key);
  if (vars) {
    for (const k of Object.keys(vars)) s = s.split('{' + k + '}').join(String(vars[k]));
  }
  return s;
}

module.exports = { LANG, t };
